name: Build Keksposé
on: [push]
jobs:
  build:
    name: Build Keksposé on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest-large => Intel, macos-latest-xlarge => arm
        os: [macos-latest-large, macos-latest-xlarge, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native Quarkus binary
        run: mvn package -Pnative

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kekspose-${{ matrix.os }}
          path: target/kekspose-*-runner*