name: Build Keksposé
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Run tests
        run: go test -v ./...
      - name: Build
        env:
          PLATFORMS: "darwin/arm64 darwin/amd64 linux/386 linux/amd64 linux/arm64 windows/amd64 windows/arm64 windows/386"
          VERSION: ${{github.ref_name}}
        run: |
          for PLATFORM in ${PLATFORMS}
          do
              PLATFORM_SPLIT=(${PLATFORM//\// })
              GOOS=${PLATFORM_SPLIT[0]}
              GOARCH=${PLATFORM_SPLIT[1]}
              OUTPUT_NAME=kekspose'-'$VERSION'-'$GOOS'-'$GOARCH
              
              echo "Building platform ${PLATFORM} as ${OUTPUT_NAME}"
              
              if [ $GOOS = "windows" ]; then
                  OUTPUT_NAME+='.exe'
              fi
          
              env GOOS=$GOOS GOARCH=$GOARCH go build -o $OUTPUT_NAME
              if [ $? -ne 0 ]; then
                  echo 'An error has occurred! Aborting the script execution...'
                  exit 1
              fi
          done
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kekspose
          path: kekspose-*
