name: Build Keksposé
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
#      - name: Test with the Go CLI
#        run: go test
      - name: Build
        run: go build
